//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatoFinalProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatoFinalProject.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHIVE.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE BLOG.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK TABLE.
        /// </summary>
        public static string BookTable {
            get {
                return ResourceManager.GetString("BookTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL US.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C H E F.
        /// </summary>
        public static string Chef {
            get {
                return ResourceManager.GetString("Chef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Cont {
            get {
                return ResourceManager.GetString("Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delicious.
        /// </summary>
        public static string Delicious {
            get {
                return ResourceManager.GetString("Delicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D I N N E R.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR EVENT BOOKING.
        /// </summary>
        public static string ForEventBooking {
            get {
                return ResourceManager.GetString("ForEventBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian Restaurant.
        /// </summary>
        public static string ItalianRestaurant {
            get {
                return ResourceManager.GetString("ItalianRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string LatestNew {
            get {
                return ResourceManager.GetString("LatestNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Twitter.
        /// </summary>
        public static string LatestTwitter {
            get {
                return ResourceManager.GetString("LatestTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string Learnmore {
            get {
                return ResourceManager.GetString("Learnmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCATION.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look Menu.
        /// </summary>
        public static string LookMenu {
            get {
                return ResourceManager.GetString("LookMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L U N C H.
        /// </summary>
        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Our.
        /// </summary>
        public static string MeetOur {
            get {
                return ResourceManager.GetString("MeetOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Menureserv {
            get {
                return ResourceManager.GetString("Menureserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOST POPULAR.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENING HOURS.
        /// </summary>
        public static string OpeningHour {
            get {
                return ResourceManager.GetString("OpeningHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Time.
        /// </summary>
        public static string OpeningTime {
            get {
                return ResourceManager.GetString("OpeningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MENU.
        /// </summary>
        public static string OurMenu {
            get {
                return ResourceManager.GetString("OurMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our story.
        /// </summary>
        public static string Ourstory {
            get {
                return ResourceManager.GetString("Ourstory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATO PLACE.
        /// </summary>
        public static string Pato {
            get {
                return ResourceManager.GetString("Pato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATO PLACE.
        /// </summary>
        public static string PatoPlace {
            get {
                return ResourceManager.GetString("PatoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVATION.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVE BY PHONE.
        /// </summary>
        public static string ReservebyTelephone {
            get {
                return ResourceManager.GetString("ReservebyTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND US A MESSAGE.
        /// </summary>
        public static string SendMsg {
            get {
                return ResourceManager.GetString("SendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Sign Up.
        /// </summary>
        public static string SpecialSignUp {
            get {
                return ResourceManager.GetString("SpecialSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Form.
        /// </summary>
        public static string SubmitForm {
            get {
                return ResourceManager.GetString("SubmitForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Pato Restaurant.
        /// </summary>
        public static string Welcometopatorestaurant {
            get {
                return ResourceManager.GetString("Welcometopatorestaurant", resourceCulture);
            }
        }
    }
}
